"""Initial tables

Revision ID: 707569c5b6c9
Revises: 
Create Date: 2026-03-05 00:38:52.613090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707569c5b6c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_specializations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_doctor_specializations_id'), 'doctor_specializations', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('specialization_id', sa.String(length=36), nullable=True),
    sa.Column('qualification', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.DECIMAL(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('rating', sa.DECIMAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_reviews', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('consultation_fee >= 0', name='check_fee_positive'),
    sa.CheckConstraint('experience_years >= 0', name='check_experience_positive'),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['specialization_id'], ['doctor_specializations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_doctors_full_name'), 'doctors', ['full_name'], unique=False)
    op.create_index(op.f('ix_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_index(op.f('ix_doctors_rating'), 'doctors', ['rating'], unique=False)
    op.create_index(op.f('ix_doctors_specialization_id'), 'doctors', ['specialization_id'], unique=False)
    op.create_table('doctor_documents',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_documents_id'), 'doctor_documents', ['id'], unique=False)
    op.create_table('doctor_education',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('year_completed', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_education_id'), 'doctor_education', ['id'], unique=False)
    op.create_table('doctor_experience',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_experience_id'), 'doctor_experience', ['id'], unique=False)
    op.create_table('doctor_hospitals',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('consultation_fee', sa.DECIMAL(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_hospitals_hospital_id'), 'doctor_hospitals', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_doctor_hospitals_id'), 'doctor_hospitals', ['id'], unique=False)
    op.create_table('doctor_languages',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_languages_id'), 'doctor_languages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_languages_id'), table_name='doctor_languages')
    op.drop_table('doctor_languages')
    op.drop_index(op.f('ix_doctor_hospitals_id'), table_name='doctor_hospitals')
    op.drop_index(op.f('ix_doctor_hospitals_hospital_id'), table_name='doctor_hospitals')
    op.drop_table('doctor_hospitals')
    op.drop_index(op.f('ix_doctor_experience_id'), table_name='doctor_experience')
    op.drop_table('doctor_experience')
    op.drop_index(op.f('ix_doctor_education_id'), table_name='doctor_education')
    op.drop_table('doctor_education')
    op.drop_index(op.f('ix_doctor_documents_id'), table_name='doctor_documents')
    op.drop_table('doctor_documents')
    op.drop_index(op.f('ix_doctors_specialization_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_rating'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_hospital_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_full_name'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_doctor_specializations_id'), table_name='doctor_specializations')
    op.drop_table('doctor_specializations')
    # ### end Alembic commands ###
