"""Add doctor_licenses, doctor_kyc tables and approval fields

Revision ID: fa57830f27fd
Revises: 707569c5b6c9
Create Date: 2026-03-07 23:37:22.368891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa57830f27fd'
down_revision: Union[str, Sequence[str], None] = '707569c5b6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM types first (PostgreSQL requires explicit type creation)
    # Using DO block to catch duplicate_object exception since 'CREATE TYPE ... IF NOT EXISTS' isn't supported directly
    op.execute('''
    DO $$ 
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_status_enum') THEN
            CREATE TYPE approval_status_enum AS ENUM ('pending', 'approved', 'rejected');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'license_status_enum') THEN
            CREATE TYPE license_status_enum AS ENUM ('pending_review', 'approved', 'rejected');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'kyc_status_enum') THEN
            CREATE TYPE kyc_status_enum AS ENUM ('not_submitted', 'pending', 'approved', 'rejected');
        END IF;
    END
    $$;
    ''')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_kyc',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_document_url', sa.Text(), nullable=True),
    sa.Column('pan_document_url', sa.Text(), nullable=True),
    sa.Column('selfie_url', sa.Text(), nullable=True),
    sa.Column('kyc_status', sa.Enum('not_submitted', 'pending', 'approved', 'rejected', name='kyc_status_enum', create_type=False, native_enum=False), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_kyc_doctor_id'), 'doctor_kyc', ['doctor_id'], unique=True)
    op.create_index(op.f('ix_doctor_kyc_id'), 'doctor_kyc', ['id'], unique=False)
    op.create_table('doctor_licenses',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_document_url', sa.Text(), nullable=False),
    sa.Column('license_document_type', sa.String(length=10), nullable=False),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', name='license_status_enum', create_type=False, native_enum=False), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_licenses_doctor_id'), 'doctor_licenses', ['doctor_id'], unique=True)
    op.create_index(op.f('ix_doctor_licenses_id'), 'doctor_licenses', ['id'], unique=False)
    op.add_column('doctors', sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='approval_status_enum', create_type=False, native_enum=False), nullable=True))
    op.execute("UPDATE doctors SET approval_status = 'pending' WHERE approval_status IS NULL")
    op.alter_column('doctors', 'approval_status', nullable=False)
    op.add_column('doctors', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doctors', sa.Column('approved_by', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'approved_by')
    op.drop_column('doctors', 'approved_at')
    op.drop_column('doctors', 'approval_status')
    op.drop_index(op.f('ix_doctor_licenses_id'), table_name='doctor_licenses')
    op.drop_index(op.f('ix_doctor_licenses_doctor_id'), table_name='doctor_licenses')
    op.drop_table('doctor_licenses')
    op.drop_index(op.f('ix_doctor_kyc_id'), table_name='doctor_kyc')
    op.drop_index(op.f('ix_doctor_kyc_doctor_id'), table_name='doctor_kyc')
    op.drop_table('doctor_kyc')
    # ### end Alembic commands ###
