"""Initial hospital service tables

Revision ID: b64a1fb40085
Revises: 
Create Date: 2026-03-08 00:49:54.029318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64a1fb40085'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.Text(), nullable=True),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(precision=53), nullable=True),
    sa.Column('longitude', sa.Float(precision=53), nullable=True),
    sa.Column('rating', sa.DECIMAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_reviews', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_latitude'), 'hospitals', ['latitude'], unique=False)
    op.create_index(op.f('ix_hospitals_longitude'), 'hospitals', ['longitude'], unique=False)
    op.create_index(op.f('ix_hospitals_organization_id'), 'hospitals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hospitals_rating'), 'hospitals', ['rating'], unique=False)
    op.create_table('hospital_facilities',
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_facilities_hospital_id'), 'hospital_facilities', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_facilities_id'), 'hospital_facilities', ['id'], unique=False)
    op.create_table('hospital_images',
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_images_hospital_id'), 'hospital_images', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_images_id'), 'hospital_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_images_id'), table_name='hospital_images')
    op.drop_index(op.f('ix_hospital_images_hospital_id'), table_name='hospital_images')
    op.drop_table('hospital_images')
    op.drop_index(op.f('ix_hospital_facilities_id'), table_name='hospital_facilities')
    op.drop_index(op.f('ix_hospital_facilities_hospital_id'), table_name='hospital_facilities')
    op.drop_table('hospital_facilities')
    op.drop_index(op.f('ix_hospitals_rating'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_organization_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_longitude'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_latitude'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
